### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by johannesschobel** [sgomez/iam-ddd-cqrs-es-nestjs#8]
Dear @sgomez ,

first of all, i would like to thank you for this **truly awesome** repository. This is the most complex / complete repository for crqs, event sourcing and nestjs i have found so far.. :+1: big shoutout to you - i really appreciate it!

However, when browsing through your code, i stumbled upon some questions i was not able to answer by myself. It would be very kind of you, if you provide me with some more details on specific areas.

1) Currently, this repository holds one "module" that is called `Scope`. Within this module, all domain aspects are stored (i.e., the commands, events, business logic and so on). In the `Scope` model, however, you have a dedicated `ScopeId` and `ScopeName` model which only holds one string variable. Is there a specific reason to do this? Why not just use normal `name: string` definitions here?

2) How would new "modules" be implemented? Do they live next to the `scope` module? e.g., a `user` module which holds all aspects of this domain, like the events (`UserWasCreatedEvent`, ...), commands (`UserChangesProfileCommand`) and so on..

3) Do you assign all events to a single main `AggregateRoot`? Consider the following example: You have the typical `Author` and `Books` model. Are those 2 "modules" with their specific commands, events, ... ? Because some events would be "cross-module" - like the `AuthorHasPublishedBookEvent`, which assigns a book to a specific author. Where is this Event stored (book or author module)? Do you have a dedicated stream for each author and then there is a `AuthorPublishedBookEvent` in this particular stream of author X? Are there `authors` and `books` streams?

I hope you get what i mean with these questions? Looking forward to hear from you.
Thank you very much for your time helping me out with this..

All the best

**Comment by sgomez** [comment]
Hi @johannesschobel.

Indeed, the repo is not finished, because I have no time right now. It's a POC from this another one I did with PHP https://github.com/aulasoftwarelibre/iam

1. ScopeId and ScopeName are Value Objects, not entities.
2. Yes, you create a new module for each new aggregate.
3. Yes, any event did inside an aggregate root belongs to it. In your example should be BookWasPublished and belongs to Book aggregate, because Author aggregate should exists before the Book does. BookWasPublished only has AuthorId (a Value Object) from the Author aggregate and nothing else. There no such thing like cross-aggregate domain events, not as far has I know. A domain event occurs inside the aggregate you changed. In the eventstore server each aggregate instance has its own stream (they say it can manage millions of them, so...).

**Comment by johannesschobel** [comment]
Dear @sgomez ,

thank you so much for your answer on this topic. Regarding your answers:
1) Is there a specific reason that you use a `ValueObject` and not just a simple `string`? For example, the `UserName` only holds a string - so what exactly is the benefit in this case?
2) ok
3) ok, so so you basically would have `author` and `book` on the same level. This, in turn, also means, that you have a stream for `author 0815` (e.g., with all his `AuthorWasCreated` and `AuthorWasChanged` events) and you have a `book 1234` stream, with a `BookWasCreated` and `BookWasPublished` event), right? Basically every object to be persisted has its own (!) stream, right? Those streams, in turn, are "linked" via values in particular events. For example, the `BookWasPublished` event may have an `authorId` property.. Is this correct?

Thank you so much for your time and help!

**Comment by sgomez** [comment]
1. Because a value object has business rules and a string doesn't. This is something basic in DDD.
3. Yes. That's right.

Any time.
